export const Text = {
    ServerError: {
        "en": "Server Error",
        "zh-TW": "伺服器錯誤",
        "ja": "サーバーエラー",
        "ko": "서비스 오류",
        "es": "Error del servidor",
        "pt": "Erro do Servidor",
        "fil": "Error ng server",
        "id": "Kesalahan Server",
        "it": "Errore del server",
    },
    Back: {
        "en": "Back",
        "zh-TW": "返回",
        "ja": "戻る",
        "ko": "돌아가기",
        "es": "Volver",
        "pt": "Voltar",
        "fil": "Bumalik",
        "id": "Kembali",
        "it": "Indietro",
    },
    Empty: {
        "zh-TW": "暫無記錄",
        "en": "No record found",
        "ja": "記録はまだありません",
        "ko": "기록이 없습니다",
        "es": "No se ha encontrado ningún registro",
        "pt": "Nenhum registro encontrado",
        "fil": "Walang natagpuat",
        "id": "Tidak ada catatan yang ditemukan",
        "it": "Nessun record trovato",
    },
    Loading: {
        "en": "loading",
        "zh-TW": "載入中",
        "ja": "ローディング中",
        "ko": "로딩 중",
        "es": "Carga",
        "pt": "Carregamento",
        "fil": "Pag-loadad",
        "id": "Memuat",
        "it": "Caricamento",
    },
    Search: {
        "zh-TW": "尋找更多短劇",
        "en": "Discover more dramas",
        "ja": "ショートドラマをもっと探す",
        "ko": "더 많은 단편 드라마 찾기",
        "es": "Descubre más dramas",
        "pt": "Descubra mais dramas",
        "fil": "Higit pang mga dramas",
        "id": "Temukan drama lainnya",
        "it": "Scopri altri drammi",
    },
    SearchBtn: {
        "zh-TW": "搜索",
        "en": "Search",
        "ja": "検索",
        "ko": "검색",
        "es": "Búsqueda",
        "pt": "Pesquisa",
        "fil": "Paghahanap",
        "id": "Pencarian",
        "it": "Ricerca"
    },
    NoMore: {
        "en": "No More",
        "zh-TW": "沒有更多了",
        "ja": "これ以上ありません",
        "ko": "더 이상 없습니다",
        "es": "No más",
        "pt": "Não Mais",
        "fil": "Walang Himo",
        "id": "Tidak ada lagi",
        "it": "Non c' è più",
    },
    WatchUpToEpisode: {
        "en": "Watch Up to Episode",
        "zh-TW": "觀看至",
        "ja": "視聴済み：話",
        "ko": "시청 완료",
        "es": "Ver hasta el episodio",
        "pt": "Assista até o episódio",
        "fil": "Panok sa Episode",
        "id": "Tonton hingga Episode",
        "it": "Guarda fino all'episodio",
    },
    LoginEmailToast: {
        "en": "Login to keep your viewing progress intact",
        "zh-TW": "请登录账号以維持您的觀看進度",
        "ja": "ログインすると視聴履歴が保存されます",
        "ko": "시청 진행 상황을 유지하려면 계정에 로그인해 주세요.",
        "es": "Inicie sesión para mantener su progreso de visualización intacto",
        "pt": "Faça login para manter o progresso do seu visualizando intacto",
        "fil": "Login upang mapanatili ang iyong pag-unlad sa panonoon",
        "id": "Masuk untuk menjaga kemajuan melihat Anda utuh",
        "it": "Accedi per mantenere intatti i tuoi progressi di visualizzazione",
    },
    OrderWaitToast: {
        "en": "The order may take a while to complete. If it doesn't take effect after payment, please try refreshing.",
        "zh-TW": "訂單可能需要一段時間才能完成。如付款後未生效，請嘗試重新整理。",
        "ja": "ご注文の処理には時間がかかる場合があります。お支払い後に反映されない場合は、ページを更新してみてください。",
        "ko": "주문 처리에는 다소 시간이 걸릴 수 있습니다. 결제 후에도 적용되지 않는 경우, 새로고침해 보시기 바랍니다.",
        "es": "La orden puede tardar un tiempo en completarse. Si no tiene efecto después del pago, intente refrescar.",
        "pt": "O pedido pode demorar um pouco para ser concluído. Se não tiver efeito após o pagamento, tente atualizar.",
        "fil": "Ang order ay maaaring tumagal ng isang oras upang makumpleto. Kung hindi ito magkakaroon ng epekto pagkatapos ng pagbabayad, mangyaring subukang mag-refresshing.",
        "id": "Pesanan mungkin membutuhkan waktu beberapa saat untuk menyelesaikan. Jika tidak berlaku setelah pembayaran, coba Segarkan.",
        "it": "L'ordine potrebbe richiedere del tempo per essere completato. Se non ha effetto dopo il pagamento, prova ad aggiornare.",
    },
    Purchased: {
        "en": "Purchased",
        "zh-TW": "已購買",
        "ja": "購入済み",
        "ko": "이미 구매함",
        "es": "Comprado",
        "pt": "Comprado",
        "fil": "Binili",
        "id": "Dibeli",
        "it": "Acquistato",
    },
    Paid: {
        "en": "Paid",
        "zh-TW": "已付款",
        "ja": "支払い済み",
        "ko": "결제 완료",
        "es": "Pagado",
        "pt": "Pago",
        "fil": "Paad",
        "id": "Dibayar",
        "it": "Pagato",
    },
    Purchase: {
        "en": "Full Series",
        "zh-TW": "全集",
        "ja": "全話",
        "ko": "전편",
        "es": "Serie completa",
        "pt": "Série completa",
        "fil": "Buong Seryes",
        "id": "Seri penuh",
        "it": "Serie completa",
    },
    PaymentChoice: {
        "en": "Please choice a payment",
        "zh-TW": "請選擇一種付款方式",
        "ja": "支払い方法",
        "ko": "결제 수단을 선택해 주세요",
        "es": "Por favor, elija un pago",
        "pt": "Por favor escolha um pagamento",
        "fil": "Mangyaring pumili ng pagbabayad",
        "id": "Silakan pilih pembayaran",
        "it": "Si prega di scegliere un pagamento",
    },
    PriceDesc: {
        "en": "{n} to unlock the full series",
        "zh-TW": "{n}解鎖全集",
        "ja": "{n}で全話アンロック",
        "ko": "{n}으로 전체 회차 해제",
        "es": "{n} para desbloquear toda la serie",
        "pt": "{n} para desbloquear a série completa",
        "fil": "{n} para ma-unlock ang buong serye",
        "id": "{n} untuk membuka semua episode",
        "it": "{n} per sbloccare l’intera serie",
    },
    PayAds: {
        "en": "Watch ads to unlock the episode",
        "zh-TW": "觀看 廣告解鎖劇集",
        "ja": "広告を本見てエピソードをアンロック",
        "ko": "광고개를 보고 에피소드를 잠금 해제",
        "es": "Veranuncios para desbloquear el episodio",
        "pt": "Assista a anúncios para desbloquear o episódio",
        "fil": "Tingnan ang ad upang i-unlock ang episodes",
        "id": "Tonton iklan untuk membuka episode",
        "it": "Guarda annunci per sbloccare l'episodio",
    },
    PayAdsNeedMore: {
        "en": "$ more ads to unlock the episode",
        "zh-TW": "還差 $ 則廣告解鎖劇集",
        "ja": "あと $ 本の広告でエピソードをアンロック",
        "ko": "에피소드를 잠금 해제하려면 광고 $ 개가 더 필요합니다",
        "es": "Faltan $ anuncios para desbloquear el episodio.",
        "pt": "Faltam $ anúncios para desbloquear o episódio.",
        "fil": "Kailangan pa ng $ na ad para ma-unlock ang episode.",
        "id": "Masih perlu $ iklan untuk membuka episode.",
        "it": "Mancano $ annunci per sbloccare l’episodio."
    },
    PayAdsSuccess: {
        "en": "Episode unlocked successfully",
        "zh-TW": "解鎖劇集成功",
        "ko": "에피소드 잠금 해제 성공",
        "ja": "エピソードのロックを解除しました",
        "es": "Episodio desbloqueado con éxito",
        "pt": "Episódio desbloqueado com sucesso",
        "fil": "Matagumpay na nag-unlock ng episodes",
        "id": "Episode berhasil membuka kunci",
        "it": "Episodio sbloccato con successo",
    },
    PayAdsNotFinish: {
        "en": "Ad task not completed, please try again.",
        "zh-TW": "未完成廣告任務，請再次嘗試。",
        "ja": "広告タスクが完了していません。もう一度お試しください。",
        "ko": "광고 작업이 완료되지 않았습니다. 다시 시도해주세요.",
        "es": "La tarea del anuncio no se ha completado, inténtelo de nuevo.",
        "pt": "Tarefa do anúncio não concluída, tente novamente.",
        "fil": "Hindi nakumpleto ang ad task, mangyaring subukan muli.",
        "id": "Tugas iklan belum selesai, coba lagi.",
        "it": "Attività dell'annuncio non completata, riprova.",
    },
    Share: {
        "en": "Share",
        "zh-TW": "分享",
        "ja": "共有する",
        "ko": "공유하다",
        "es": "Compartir",
        "pt": "Compartilhar",
        "fil": "I-share",
        "id": "Bagikan",
        "it": "Condividi",
    },
    ShareDesc: {
        "en": <>Like this drama? <br/>Share it with your friends and watch together!</>,
        "zh-TW": <>喜歡這部劇，<br/>分享給好友一起看吧</>,
        "ja": <>このドラマが気に入りましたか？<br/>友達と一緒に観ましょう！</>,
        "ko": <>이 드라마가 마음에 드세요?<br/>친구와 함께 보세요!</>,
        "es": <>¿Te gusta esta serie?<br/>¡Compártela con tus amigos para verla juntos!</>,
        "pt": <>Gostou desta série?<br/>Compartilhe com seus amigos para assistirem juntos!</>,
        "fil": <>Gusto mo ba ang palabas na ito?<br/>I-share ito sa iyong mga kaibigan para sabay kayong manood!</>,
        "id": <>Suka dengan serial ini?<br/>Bagikan ke teman-temanmu untuk menontonnya bersama!</>,
        "it": <>Ti piace questa serie?<br/>Condividila con i tuoi amici per guardarla insieme!</>,
    },
    Card: {
        "en": <>,<br/>Unlimited View All Dramas For A Week</>,
        "zh-TW": <>,<br/>一週內無限觀看全站劇集</>,
        "ja": <>,<br/>1週間、すべてのドラマを無制限で視聴</>,
        "ko": <>,<br/>일주일 동안 모든 드라마 무제한 시청</>,
        "es": <>,<br/>Visualización ilimitada de todos los dramas durante una semana</>,
        "pt": <>,<br/>Visualização ilimitada de todos os dramas por uma semana</>,
        "fil": <>,<br/>Walang limitasyong panonood ng lahat ng drama sa loob ng isang linggo</>,
        "id": <>,<br/>Tonton semua drama tanpa batas selama satu minggu</>,
        "it": <>,<br/>Visione illimitata di tutti i drammi per una settimana</>,
    },
    PlayNext: {
        "en": "{m} will start in {n} seconds",
        "zh-TW": "{m} 將在 {n} 秒後播出",
        "ja": "{m} は {n} 秒後に放送開始",
        "ko": "{m}이(가) {n}초 후에 방송됩니다",
        "es": "{m} se emitirá en {n} segundos",
        "pt": "{m} será transmitido em {n} segundos",
        "fil": "Mag-uumpisa ang {m} sa loob ng {n} segundo",
        "id": "{m} akan ditayangkan dalam {n} detik",
        "it": "{m} inizierà tra {n} secondi",
    },
    Free: {
        "en": "Unlimited",
        "zh-TW": "無限",
        "ja": "無制限",
        "ko": "무제한",
        "es": "Ilimitado",
        "pt": "Ilimitado",
        "fil": "Walang limitasyon",
        "id": "Tak terbatas",
        "it": "Illimitato",
    },
    Login: {
        "en": "Login",
        "zh-TW": "登入",
        "ja": "ログイン",
        "ko": "로그인",
        "es": "Login",
        "pt": "Login",
        "fil": "Login",
        "id": "Masuk",
        "it": "Accesso",
    },
    PlayNow: {
        "en": "Play Now",
        "zh-TW": "立即播放",
        "ja": "今すぐプレイ",
        "ko": "바로 재생하기",
        "es": "Jugar ahora",
        "pt": "Jogar Agora",
        "fil": "Pag-play ngayon",
        "id": "Main sekarang",
        "it": "Gioca ora",
    },
    Store: {
        "en": "Store",
        "zh-TW": "商店",
        "ja": "ストア",
        "ko": "가게",
        "es": "Tienda",
        "pt": "Loja",
        "fil": "Store",
        "id": "Toko",
        "it": "Negozio",
    },
    EmailInput: {
        "en": "input your email",
        "zh-TW": "輸入您的電子郵件",
        "ja": "メールアドレスを入力してください。",
        "ko": "이메일 주소를 입력해 주세요.",
        "es": "Ingrese su correo electrónico",
        "pt": "Insira seu email",
        "fil": "Input ng iyong email",
        "id": "Masukkan email Anda",
        "it": "Inserisci la tua email",
    },
    CodeInput: {
        "en": "email verify code",
        "zh-TW": "電子郵件驗證碼",
        "ja": "メール認証コード",
        "ko": "이메일 인증 코드",
        "es": "Correo electrónico verificar código",
        "pt": "Email verificar código",
        "fil": "Email verify code",
        "id": "Kode verifikasi email",
        "it": "Codice verifica e-mail",
    },
    EmailSuccess: {
        "en": "Email sent successfully. Pls Check your email",
        "zh-TW": "驗證郵件已送出，請檢查您的信箱",
        "ja": "メールが正常に送信されました。メールをご確認ください。",
        "ko": "인증 메일이 발송되었습니다. 메일함을 확인해 주세요.",
        "es": "Correo electrónico enviado correctamente. Pls Compruebe su correo electrónico",
        "pt": "Email enviado com sucesso. Pls Verifique seu email",
        "fil": "Ipinadala ang email nang matagumpay. Pls Check ang iyong email...",
        "id": "Email berhasil dikirim. Harap periksa email Anda",
        "it": "Email inviata con successo. Controlla la tua email",
    },
    EmailFailure: {
        "en": "Email send failed.Pls try again",
        "zh-TW": "驗證郵件發送失敗，請再試一次",
        "ja": "メールの送信に失敗しました。もう一度お試しください。",
        "ko": "인증 메일 전송에 실패했습니다. 다시 시도해 주세요.",
        "es": "Enviar correo electrónico falló. Pls inténtelo de nuevo",
        "pt": "Email enviar falhou. Pls tentar novamente",
        "fil": "Nabigo ang pagpapadala ng email.Pls subukan muli.Pls subukang",
        "id": "Pengiriman Email gagal. Silakan coba lagi",
        "it": "Invio e-mail non riuscito. Riprova",
    },
    GetCode: {
        "en": "Get Code",
        "zh-TW": "獲取驗證碼",
        "ja": "コードを取得",
        "ko": "인증 코드 받기",
        "es": "Obtener código",
        "pt": "Obter Código",
        "fil": "Kuha ng Code",
        "id": "Dapatkan kode",
        "it": "Ottieni codice",
    },
    EmailCodeExpire: {
        "en": "Email verify code expire.Pls try again",
        "zh-TW": "驗證碼已過期，請重新取得",
        "ja": "認証コードの期限切れです。再度お試しください。",
        "ko": "인증 코드가 만료되었습니다. 다시 받아 주세요.",
        "es": "Correo electrónico verificar el código expirar. Pls inténtelo de nuevo",
        "pt": "Email verificar código expirar. Pls tentar novamente",
        "fil": "Mag-expire ng email code.Pls subukan muli ang Pls",
        "id": "Kode verifikasi Email kedaluwarsa. Mohon coba lagi",
        "it": "Il codice di verifica e-mail scade. Riprova",
    },
    LoginFail: {
        "en": "Login failed.Pls try again",
        "zh-TW": "登入失敗，請再試一次",
        "ja": "ログイン失敗。再度お試しください。",
        "ko": "로그인에 실패했습니다. 다시 시도해 주세요.",
        "es": "Inicio de sesión falló. Pls inténtelo de nuevo",
        "pt": "Login falhou. Pls tente novamente",
        "fil": "Nabigo ang Login.Pls subukan mulin",
        "id": "Gagal masuk. Coba lagi",
        "it": "Accesso non riuscito. Prova di nuovo",
    },
    Confirm: {
        "en": "Confirm",
        "zh-TW": "確認",
        "ja": "確認",
        "ko": "확인 ",
        "es": "Confirmar",
        "pt": "Confirmar",
        "fil": "Pagkumpirma",
        "id": "Konfirmasi",
        "it": "Conferma",
    },
    About: {
        "en": "About",
        "zh-TW": "關於",
        "ja": "会社概要",
        "ko": "관하여",
        "es": "Acerca de",
        "pt": "Sobre",
        "fil": "Tungkol",
        "id": "Tentang",
        "it": "A proposito",
    },
    TermsOfService: {
        "en": "Terms of Service",
        "zh-TW": "服務條款",
        "ja": "利用規約",
        "ko": "서비스 약관",
        "es": "Términos de servicio",
        "pt": "Termos de Serviço",
        "fil": "Mga termino ng Serbisyo",
        "id": "Ketentuan Layanan",
        "it": "Termini di servizio",
    },
    PrivacyPolicy: {
        "en": "Privacy Policy",
        "zh-TW": "隱私政策",
        "ja": "個人情報保護方針",
        "es": "Política de privacidad",
        "pt": "Política Privacidade",
        "fil": "Privacy Policy",
        "id": "Kebijakan Privasi",
        "it": "Politica sulla privacy",
    },
    FAQ: {
        "en": "FAQ",
        "zh-TW": "常見問題",
        "ja": "よくある質問",
        "ko": "FAQ",
        "es": "Preguntas frecuentes",
        "pt": "FAQ",
        "fil": "FAQ",
        "id": "FAQ",
        "it": "FAQ",
    },
    ContactUs: {
        "en": "Contact Us",
        "zh-TW": "聯絡我們",
        "ja": "ご連絡ください",
        "ko": "문의하기",
        "es": "Contacte con nosotros",
        "pt": "Fale Conosco",
        "fil": "Contact Aming",
        "id": "Hubungi kami",
        "it": "Contattaci",
    },
    Community: {
        "en": "Community",
        "zh-TW": "社群",
        "ja": "コミュニティ",
        "ko": "커뮤니티",
        "es": "Comunidad",
        "pt": "Comunidade",
        "fil": "Komunidada",
        "id": "Komunitas",
        "it": "Comunità",
    },
    DownloadApp:{
        "en": "Download App",
        "zh-TW": "下載應用程式",
        "ja": "アプリをダウンロード",
        "ko": "앱 다운로드",
        "es": "Descargar App",
        "pt": "Baixar aplicativo",
        "fil": "Download App",
        "id": "Unduh Aplikasi",
        "it": "Scarica l'app",
    },
    BottomLine: {
        "en": "NetShort | All Rights Reserved | 2024 NETSTORY PTE. LTD.",
        "zh-TW": "NetShort | 版權所有 | 2024 NETSTORY PTE. LTD.",
        "ja": "NetShort | 全著作権所有 | 2024 NETSTORY PTE. LTD.",
        "ko": "NetShort | 모든 저작권 소유 | 2024 NETSTORY PTE. LTD.",
        "es": "NetShort | Todos los derechos reservados | 2024 NETSTORY PTE. LTD.",
        "pt": "NetShort | Todos os direitos reservados | 2024 NETSTORY PTE. LTD.",
        "fil": "NetShort | Lahat ng Karapatan ay Reserved | 2024 NETSTORY PTE. LTD.",
        "id": "NetShort | Semua hak cipta reservasi | 2024 NETSTORY PTE. LTD.",
        "it": "NetShort | Tutti i diritti riservati | 2024 NETSTORY PTE. LTD.",
    },
    NotFound: {
        "en": "404 Not Found",
        "zh-TW": "404 網頁不存在",
        "ja": "404 見つかりません",
        "ko": "404 페이지를 찾을 수 없습니다",
        "es": "404 No encontrado",
        "pt": "404 Não encontrado",
        "fil": "404 Hindi nahanap",
        "id": "404 tidak ditemukan",
        "it": "404 Non Trovato",
    },
    DramaFinish: {
        "en": "Drama Finish...",
        "zh-TW": "劇集已完結…",
        "ja": "ドラマ終了…",
        "ko": "드라마가 이미 종료되었습니다...",
        "es": "Drama Finish...",
        "pt": "Drama Finish...",
        "fil": "Drama finish...",
        "id": "Drama selesai...",
        "it": "Drama Finish...",
    },
    NeedPurchase: {
        "en": "Need Purchase",
        "zh-TW": "需要購買",
        "ja": "購入が必要",
        "ko": "구매가 필요합니다",
        "es": "Necesidad de compra",
        "pt": "Precisa Comprar",
        "fil": "Kailangang bumili",
        "id": "Perlu membeli",
        "it": "Hai bisogno di acquisto",
    },
    Next: {
        "en": "Next",
        "zh-TW": "下一集",
        "ja": "次の",
        "ko": "다음 편",
        "es": "Siguiente",
        "pt": "Próximo",
        "fil": "Susunoda",
        "id": "Berikutnya",
        "it": "Successivo",
    },
    QuestionPurchase: {
        "en": "Purchase or After-sales Issues?",
        "zh-TW": "購買或售後問題",
        "ja": "購入またはアフターサービスのご質問ですか？",
        "ko": "구매 및 A/S 관련 문제",
        "es": "¿Problemas de compra o post-venta?",
        "pt": "Compras ou problemas pós-venda?",
        "fil": "Pagbili o After-sales Issues?",
        "id": "Pembelian atau masalah purnajual?",
        "it": "Problemi di acquisto o post-vendita?",
    },
    QuestionSuggestion: {
        "en": "Some Suggestions",
        "zh-TW": "一些建議",
        "ja": "いくつかの提案",
        "ko": "몇 가지 의견",
        "es": "Algunas sugerencias",
        "pt": "Algumas Sugestões",
        "fil": "Ilang mga mungkahi",
        "id": "Beberapa saran",
        "it": "Alcuni suggerimenti",
    },
    QuestionCollaboration: {
        "en": "Ideas for Collaboration",
        "zh-TW": "有些創意想合作",
        "ja": "コラボレーションのアイデア",
        "ko": "몇 가지 아이디어로 협력하고 싶습니다",
        "es": "Ideas para la colaboración",
        "pt": "Ideias para colaboração",
        "fil": "Mga ideya para sa Collaboration",
        "id": "Ide untuk kolaborasi",
        "it": "Idee per la collaborazione",
    },
    VideoNo: {
        "en": "Episode:",
        "zh-TW": "戏集：",
        "ja": "話:",
        "ko": "드라마: ",
        "es": "Episodio:",
        "pt": "Episódio:",
        "fil": "Episode:",
        "id": "Episode:",
        "it": "Episodio:",
    },
    Recommend: {
        "en": "Top Series for You",
        "zh-TW": "劇集推薦",
        "ja": "あなたへのおすすめトップシリーズ",
        "ko": "드라마 추천",
        "es": "Top Series para ti",
        "pt": "Top Series para você",
        "fil": "Top Series para sa Iw",
        "id": "Seri atas untuk Anda",
        "it": "Serie top per te",
    },
    CompleteSeries: {
        "en": "Full Series",
        "zh-TW": "全集",
        "ja": "全話セット",
        "ko": "전편",
        "es": "Serie completa",
        "pt": "Série completa",
        "fil": "Buong Seryes",
        "id": "Seri penuh",
        "it": "Serie completa",
    },
    More: {
        "zh-TW": "更多推荐的好剧",
        "en": "More Top Recommended Shows",
        "ja": "もっとおすすめの名作ドラマ",
        "ko": "더 많은 추천 명작",
        "es": "Más Top Shows recomendados",
        "pt": "Mais Top Shows recomendados",
        "fil": "Mas Top Recomkomend Shows",
        "id": "Pameran rekomendasi teratas lainnya",
        "it": "Altri spettacoli più consigliati",
    },
    EmailLogin: {
        "zh-TW": "電子信箱登入",
        "en": "Email Login",
        "ja": "メールログイン",
        "ko": "이메일로 로그인하기",
        "es": "Inicio de sesión por correo electrónico",
        "pt": "Login Email",
        "fil": "Email Login",
        "id": "Masuk Email",
        "it": "Accesso e-mail",
    },
    AccountLogin: {
        "zh-TW": "帳號密碼登入",
        "en": "Account Login",
        "ja": "パスワードログイン",
        "ko": "아이디와 비밀번호로 로그인하기",
        "es": "Inicio de sesión de cuenta",
        "pt": "Conta Login",
        "fil": "Account Login",
        "id": "Masuk akun",
        "it": "Accesso account",
    },
    AccountInput: {
        "zh-TW": "输入您的帳號",
        "en": "Input your account",
        "ja": "アカウントを入力",
        "ko": "계정을 입력해 주세요",
        "es": "Ingresar su cuenta",
        "pt": "Insuma sua conta",
        "fil": "Input ng iyong account.",
        "id": "Masukkan Akun Anda",
        "it": "Inserisci il tuo account",
    },
    PasswordInput: {
        "zh-TW": "輸入您的密碼",
        "en": "Input your password",
        "ja": "パスワードを入力",
        "ko": "비밀번호를 입력해 주세요",
        "es": "Ingresar su contraseña",
        "pt": "Insita sua senha",
        "fil": "Input ng iyong password",
        "id": "Masukkan kata sandi Anda",
        "it": "Inserisci la tua password",
    },
    PasswordAgainInput: {
        "zh-TW": "再次輸入您的密碼",
        "en": "Input your password again",
        "ja": "パスワードを再入力してください",
        "ko": "비밀번호를 다시 입력해 주세요",
        "es": "Ingresar su contraseña nuevamente",
        "pt": "Insita sua senha novamente",
        "fil": "Input muli ang iyong password.",
        "id": "Masukkan kembali kata sandi Anda",
        "it": "Inserisci di nuovo la tua password",
    },
    RegisterTip: {
        "zh-TW": "若您輸入的是未註冊的帳號，我們將自動建立新帳號。",
        "en": "A new account will be created if the username you enter is not registered",
        "ja": "未登録のアカウントを入力された場合、自動で新規アカウントを作成します。",
        "ko": "입력하신 계정이 등록되지 않은 경우, 자동으로 새 계정을 생성합니다.",
        "es": "Se creará una nueva cuenta si el nombre de usuario introducido no está registrado.",
        "pt": "Uma nova conta será criada se o usuário que você digitar não estiver registrado",
        "fil": "Isang bagong account ay lilikha kung ang username na ipasok mo ay hindi nakarekord",
        "id": "Akun baru akan dibuat jika nama pengguna yang Anda masukkan tidak terdaftar",
        "it": "Un nuovo account verrà creato se il nome utente inserito non è registrato",
    },
    AccountTip: {
        "zh-TW": "僅限 a-z、A-Z、0-9、底線，且須以字母開頭，長度為 6 至 12 個字元",
        "en": "a-z,A-Z, 0-9, _, start with letter, 6–12 chars",
        "ja": "a〜z、A〜Z、0〜9、アンダースコアのみ使用可能で、先頭は英字で、長さは6〜12文字です",
        "ko": "a-z, A-Z, 0-9, 밑줄(_)만 허용되며, 반드시 문자로 시작해야 하고, 길이는 6자에서 12자 사이여야 합니다",
        "es": "A-z, A-Z, 0-9, _, comenzar con letra, 6-12 caracteres",
        "pt": "A-z,A-Z, 0-9, _, começa com letra, 6-12 caracteres",
        "fil": "A-z, A-Z, 0-9, _, nagsisimula sa titik, 6-12 chars",
        "id": "A-Z, A-Z, 0-9, _, mulai dengan huruf, 6-12 gunting",
        "it": "A-z,A-Z, 0-9, _, inizia con la lettera, 6-12 pezzi",
    },
    PasswordTip: {
        "zh-TW": "僅限 a-z、A-Z、0-9、符號，長度 6–10 個字元",
        "en": "a-z, A-Z, 0-9, symbols, 6–10 chars",
        "ja": "a〜z、A〜Z、0〜9、記号のみ使用可能で、長さは6〜10文字です。",
        "ko": "a-z, A-Z, 0-9 및 특수문자만 허용되며, 길이는 6~10자입니다",
        "es": "A-z, A-Z, 0-9, símbolos, 6-10 caracteres",
        "pt": "A-z, A-Z, 0-9, símbolos, 6-10 caracteres",
        "fil": "A-z, A-Z, 0-9, simbolo, 6-10 chars",
        "id": "A-Z, A-Z, 0-9, simbol, 6-10 dolar",
        "it": "A-z, A-Z, 0-9, simboli, 6-10 caratteri",
    },
    NotSamePassword: {
        "zh-TW": "兩次輸入的密碼不相同",
        "en": "The two passwords you entered are not the same",
        "ja": "パスワードが一致しません。",
        "ko": "두 번 입력한 비밀번호가 일치하지 않습니다",
        "es": "Las dos contraseñas que ha introducido no son las mismas",
        "pt": "As duas senhas que você digitou não são as mesmas",
        "fil": "Ang dalawang password na ipinasok mo ay hindi pareho...",
        "id": "Dua kata sandi yang Anda masukkan tidak sama.",
        "it": "Le due password che hai inserito non sono le stesse",
    },
    InvalidFormat: {
        "zh-TW": "錯誤的格式",
        "en": "Invalid format",
        "ja": "不正な形式です",
        "ko": "잘못된 형식",
        "es": "Formato no válido",
        "pt": "Formato inválido",
        "fil": "Hindi maliit na formato",
        "id": "Format tidak valid",
        "it": "Formato non valido",
    },
    Redeem: {
        "zh-TW": "兌換",
        "en": "Redeem",
        "ja": "交換する",
        "ko": "교환",
        "es": "Canjear",
        "pt": "Resgatar",
        "fil": "Redeem",
        "id": "Tukarkan",
        "it": "Riscatta",
    },
    RedeemTip: {
        "zh-TW": "請輸入禮品碼",
        "en": "Please input the gift code.",
        "ja": "ギフトコード入力",
        "ko": "선물 코드를 입력해 주세요",
        "es": "Por favor, introduzca el código de regalo.",
        "pt": "Por favor insira o código do presente.",
        "fil": "Mangyaring i-input ang regalo code.",
        "id": "Masukkan kode hadiah.",
        "it": "Inserisci il codice regalo.",
    },
    RedeemInsufficient: {
        "zh-TW": "此禮品碼兌換名額已用光",
        "en": "The redemption limit for this gift code has been reached.",
        "ja": "このギフトコードの交換枠はすでに使い切られています",
        "ko": "이 선물 코드 교환 가능 인원이 모두 소진되었습니다",
        "es": "Se ha alcanzado el límite de canje para este código de regalo.",
        "pt": "O limite de resgate deste código de presente foi atingido.",
        "fil": "Naabot ang limitasyon ng pagbabago para sa regalong code na ito.",
        "id": "Batas penukaran untuk kode hadiah ini telah tercapai.",
        "it": "Il limite di riscatto per questo codice regalo è stato raggiunto.",
    },
    RedeemDuplicate: {
        "zh-TW": "你已經參與過此活動",
        "en": "You have already participated in this event.",
        "ja": "すでにこのイベントに参加済みです",
        "ko": "이미 이 행사에 참여하셨습니다",
        "es": "Usted ya ha participado en este evento.",
        "pt": "Você já participou deste evento.",
        "fil": "Nakilahok ka na sa kaganapan na ito.",
        "id": "Anda sudah berpartisipasi dalam acara ini.",
        "it": "Hai già partecipato a questo evento.",
    },
    RedeemFailed: {
        "zh-TW": "兌換失敗，請重試",
        "en": "Redemption failed. Please try again.",
        "ja": "交換失敗。再度お試しください。",
        "ko": "교환에 실패했습니다. 다시 시도해 주세요.",
        "es": "Redención falló. Por favor, inténtelo de nuevo.",
        "pt": "A redenção falhou. Por favor tente novamente.",
        "fil": "Nabigo ang pagbabago. Mangyaring subukan muli.",
        "id": "Penukaran gagal. Coba lagi.",
        "it": "La redenzione non è riuscita. Riprova.",
    },
    RedeemSuccess: {
        "zh-TW": "兌換成功",
        "en": "Redemption successful",
        "ja": "交換が成功しました",
        "ko": "교환 성공",
        "es": "Redención exitosa",
        "pt": "Redenção bem sucedida",
        "fil": "Tagumpay ang pagbabad",
        "id": "Penukaran berhasil",
        "it": "Redenzione riuscita",
    },
    NoRedeem: {
        "zh-TW": "本劇暫不可使用禮品碼",
        "en": "Gift codes are currently unavailable for this show",
        "ja": "このドラマではギフトコードは利用不可です",
        "ko": "본 드라마는 현재 선물 코드를 사용할 수 없습니다",
        "es": "Los códigos de regalo no están disponibles actualmente para este espectáculo",
        "pt": "Gift codes estão atualmente indisponíveis para este show",
        "fil": "Sa kasalukuyang hindi magagamit ang mga regalong code para sa palabas na ito",
        "id": "Kode hadiah saat ini tidak tersedia untuk acara ini",
        "it": "I codici regalo non sono attualmente disponibili per questo spettacolo",
    },
    ShareTitle: {
        "zh-TW": "你想分享到哪裡？",
        "en": "Where would you like to share?",
        "ja": "どこにシェアしますか？",
        "ko": "어디에 공유하고 싶으세요?",
        "es": "¿Dónde te gustaría compartir?",
        "pt": "Onde você gostaria de compartilhar?",
        "fil": "Saan mo gustong ibahagi?",
        "id": "Di mana Anda ingin membagikan?",
        "it": "Dove vorresti condividere?",
    },
    ReviewTitle: {
        "zh-TW": "請留下你的意見",
        "en": "Please leave your feedback",
        "ja": "ご意見をお願いします",
        "ko": "의견을 남겨 주세요",
        "es": "Por favor, deja tu feedback",
        "pt": "Por favor deixe o seu feedback",
        "fil": "Mangyaring iwanan ang iyong feedback...",
        "id": "Berikan tanggapan Anda",
        "it": "Si prega di lasciare il vostro feedback",
    },
    ReviewTip: {
        "zh-TW": "請留下您的建議與聯絡方式，我們查收後會第一時間跟進與改進。若您的建議對我們有幫助，我們也會給予您一些獎勵以表感謝。",
        "en": "Please leave your suggestions and contact information. We will follow up and improve as soon as we review them. If your suggestion is helpful to us, we will also offer you a reward as a token of our appreciation.",
        "ja": "ご意見とご連絡先を残してください。確認後、すぐに対応し改善いたします。ご提案が私たちにとって有益な場合は、感謝の気持ちとして報酬を差し上げます。",
        "ko": "고객님의 의견과 연락처를 남겨주시면 확인 후 신속히 처리하고 개선하겠습니다. 고객님의 소중한 의견이 도움이 될 경우, 감사의 의미로 소정의 보상을 드립니다.",
        "es": "Por favor, deje sus sugerencias e información de contacto. Haremos un seguimiento y mejoraremos tan pronto como los revisemos. Si su sugerencia es útil para nosotros, también le ofreceremos una recompensa como muestra de nuestro agradecimiento.",
        "pt": "Por favor deixe as suas sugestões e contactos. Vamos acompanhar e melhorar assim que os revisarmos. Se a sua sugestão for útil para nós, também lhe ofereceremos uma recompensa como sinal de nossa gratidão.",
        "fil": "Mangyaring iwanan ang iyong mga mungkahi at impormasyon sa contact. Tayo ay susundin at magpapabuti sa lalong madaling pagsusuri namin ang mga ito. Kung ang iyong mungkahi ay makatulong sa amin, mag-aalok din kami ng gantimpala bilang tanda ng aming pagpapahalaga.",
        "id": "Mohon tinggalkan saran dan informasi kontak Anda. Kami akan menindaklanjuti dan memperbaiki segera setelah kami tinjau mereka. Jika saran Anda bermanfaat bagi kami, kami juga akan menawarkan hadiah kepada Anda sebagai token apresiasi kami.",
        "it": "Si prega di lasciare i vostri suggerimenti e informazioni di contatto. Seguiremo e miglioreremo non appena li esamineremo. Se il tuo suggerimento ci è utile, ti offriremo anche una ricompensa come segno del nostro apprezzamento.",
    },
    LiveAgent: {
        "zh-TW": "人工客服",
        "en": "Live Agent",
        "ja": "有人対応",
        "ko": "인간 상담원",
        "es": "Agente en vivo",
        "pt": "Agente vivo",
        "fil": "Live Agent",
        "id": "Agen langsung",
        "it": "Agente vivo",
    },
    Submit: {
        "zh-TW": "提交",
        "en": "Submit",
        "ja": "送信",
        "ko": "제출",
        "es": "Enviar",
        "pt": "Enviar",
        "fil": "Submite",
        "id": "Kirimkan",
        "it": "Invia",
    },
    RechargeTip: {
        "zh-TW": "此訂單僅用於本網站觀看",
        "en": "This order is for viewing on this website only",
        "ja": "この注文は本サイトでの視聴専用です",
        "ko": "이 주문은 본 사이트에서만 시청할 수 있습니다",
        "es": "Este pedido es solo para ver en este sitio web",
        "pt": "Este pedido é apenas para visualização neste site",
        "fil": "Ang order na ito ay para sa panonood lamang sa website na ito",
        "id": "Pesanan ini hanya untuk dilihat di Situs Web ini",
        "it": "Questo ordine è solo per la visualizzazione su questo sito web",
    },
    RechargeRecord: {
        "es": "Registro de recarga",
        "pt": "Recarregar registro",
        "fil": "Recharge Record",
        "id": "Catatan isi ulang",
        "it": "Record di ricarica",
        "zh-TW": "充值紀錄",
        "en": "Recharge Record",
        "ja": "チャージ履歴",
        "ko": "충전 기록",
    },
    WatchRecord: {
        "zh-TW": "觀看紀錄",
        "en": "Watch Record",
        "ja": "視聴履歴",
        "ko": "시청 기록",
        "es": "Reloj Record",
        "pt": "Assista Record",
        "fil": "Watch Record",
        "id": "Rekam jam",
        "it": "Guarda la registrazione",
    },
    RechargeSuccess: {
        "zh-TW": "已付款",
        "en": "Paid",
        "ja": "支払い済み",
        "ko": "결제 완료",
        "es": "Pagado",
        "pt": "Pago",
        "fil": "Paad",
        "id": "Dibayar",
        "it": "Pagato",
    },
    RechargePending: {
        "zh-TW": "等待中",
        "en": "Pending",
        "ja": "待機中",
        "ko": "대기 중",
        "es": "Pendiente",
        "pt": "Pendente",
        "fil": "Pinapatayan",
        "id": "Tertunda",
        "it": "In sospeso",
    },
    RechargeReportTip: {
        "zh-TW": "點此使用兌換碼換取短劇。回報支付異常情況，可獲得免費觀看禮品碼喔！",
        "en": "Redeem a drama using your code here. Report payment issues to get a free access gift code!",
        "ja": "ここをクリックしてコードでショートドラマをゲット！お支払いの異常を報告すると、無料視聴用のギフトコードがもらえますよ！",
        "ko": "여기를 눌러 교환 코드를 사용해 단편극을 받으세요. 결제 오류를 신고하면 무료 시청 기프트 코드를 드립니다!",
        "es": "Rema un drama usando tu código aquí. ¡Informe problemas de pago para obtener un código de regalo de acceso gratuito!",
        "pt": "Resgatar um drama usando seu código aqui. Comunicar problemas de pagamento para obter acesso gratuito código presente!",
        "fil": "Pagbabago ng drama gamit ang iyong code dito. Mga isyu sa payment upang makakuha ng libreng access regalo code!",
        "id": "Tukarkan drama dengan menggunakan kode Anda di sini. Laporkan masalah pembayaran untuk mendapatkan kode hadiah akses gratis!",
        "it": "Riscatta un dramma usando il tuo codice qui. Segnala problemi di pagamento per ottenere un codice regalo di accesso gratuito!",
    },
    SearchAll: {
        "zh-TW": "全部劇",
        "en": "All Dramas",
        "ja": "全部ドラマ",
        "ko": "전체 드라마",
        "es": "Todos los dramas",
        "pt": "Todos os Dramas",
        "fil": "Lahat ng Dramas",
        "id": "Semua drama",
        "it": "Tutti i drammi",
    },
    Continue: {
        "zh-TW": "繼續",
        "en": "Continue",
        "ja": "続ける",
        "ko": "계속",
        "es": "Continuar",
        "pt": "Continuar",
        "fil": "Magpatuloy",
        "id": "Lanjutkan",
        "it": "Continuare",
    },
    KocTitle: {
        "zh-TW": "發影片拿 <span>99,999</span> 金幣！",
        "en": "Post to Win <span>99,999</span> Bonus!",
        "ja": "投稿して <span>99,999</span> ボーナスをゲット！",
    },
    KocContent: {
        "zh-TW": "你也愛看 Netshort 的短劇嗎？現在輪到你發揮創意了！🎬<br/>拍一支短影片就能領 99,999 金幣獎勵，超簡單🔥",
        "en": "Netshort is calling all short drama lovers and content creators!🎬<br/>Post a short video & get 99,999 bonus — it’s that easy! 🔥",
    },
    KocTime: {
        "zh-TW": "7月16日至7月31日（UTC+0）",
        "en": "July 16 - July 31 (UTC+0)",
    },
    KocEnterTip1: {
        "zh-TW": "你的 IG / TikTok / YouTube / FB 有 5,000+ 粉絲",
        "en": "Post a short video (under 1 min) + caption about Netshort on any social media platform (must have 5,000+ followers)",
    },
    KocEnterTip2: {
        "zh-TW": "發一則和 Netshort 有關的短影片（1 分鐘內）+文案",
        "en": "Fill out the form after posting",
    },
    KocEnterTip3: {
        "zh-TW": "填寫表單提交",
        "en": "Once approved, you’ll get <span>99,999 bonus within 24 hours!</span>",
    },
    KocEnterTip4: {
        "zh-TW": "通過審核後，24 小時內發 99,999 金幣（金幣使用期限 7 天）",
        "en": "<span>Note:</span> Bonus must be used within <span>7 days</span> after receiving them.",
    },
    KocEnterBtn: {
        "zh-TW": "填寫表單",
        "en": "Fill Form",
    },
    KocEnterHowToEnter: {
        "zh-TW": "🎬怎麼參加",
        "en": "🎬How to Join",
    },
    KocVideoDemandTitle: {
        "zh-TW": "📌 影片內容需包含",
        "en": "📌 What to Include",
    },
    KocVideoDemandTip1: {
        "zh-TW": "📽 Netshort Logo（素材下載看下方）",
        "en": "🎥 The video must include the Netshort logo (download from Google Drive)",
    },
    KocTextDemandTitle: {
        "zh-TW": "📝 文案需包含",
        "en": "📝 Caption must include:",
    },
    KocTextDemandTip1: {
        "zh-TW": "1. 🔗 App下載連結：<a href='https://netshort.com/base/n/tm0VuEo'>https://netshort.com/base/n/tm0VuEo</a>",
        "en": "1. 🔗 Netshort app link: <a href='https://netshort.com/base/n/tm0VuEo'>https://netshort.com/base/n/tm0VuEo</a>",
    },
    KocTextDemandTip2: {
        "en": "<br/>2. 👥 Community links:<br/>" +
            " FB Group: <a href='https://api.netshort.online/pay/fb-group'>https://api.netshort.online/pay/fb-group</a><br/>" +
            " TG Group: <a href='https://t.me/+1KTeeg_zpxMwODZk'>https://t.me/+1KTeeg_zpxMwODZk</a>",
        "zh-TW": "<br/>2. 👥 社群連結：<br/>" +
            " Line 社群：<a href='https://api.netshort.online/pay/line-tw'>https://api.netshort.online/pay/line-tw</a><br/>" +
            " FB社群：<a href='https://www.facebook.com/share/g/1ANS4NPvAn/'>https://www.facebook.com/share/g/1ANS4NPvAn/</a>"
    },
    KocHashTagTitle: {
        "zh-TW": "3. 🏷 HashTag",
        "en": "3. 🏷 HashTag",
    },
    KocHashTagTip1:{
        "zh-TW": "<span class='copy'>#NetshortDramas #DownloadNetshort</span>",
        "en": "<span class='copy'>#NetshortDramas #DownloadNetshort</span>",
    },
    KocHashTagTip2:{
        "zh-TW": "@官方帳號",
        "en": "Tag the official Netshort account on your platform",
    },
    KocHashTagTip3:{
        "zh-TW": "Ins官号：<span class='copy'>@netshortdrama</span>",
        "en": "IG：<span class='copy'>@netshortdrama</span>",
    },
    KocHashTagTip4:{
        "zh-TW": "TT官号：<span class='copy'>@netshortdramas</span>",
        "en": "TikTok：<span class='copy'>@netshortdramas</span>",
    },
    KocHashTagTip5:{
        "zh-TW": "YT官号：<span class='copy'>@NetShort - Popular Dramas & TV</span>",
        "en": "YouTube：<span class='copy'>@NetShort - Popular Dramas & TV</span>",
    },
    KocHashTagTip6:{
        "zh-TW": "FB官号：<span class='copy'>@Netshort Drama</span>",
        "en": "FB：<span class='copy'>@Netshort Drama</span>",
    },
    KocContentTitle: {
        "zh-TW": "📁 影片素材來源",
        "en": "📁 Need Content?",
    },
    KocContentTip1: {
        "zh-TW": "從 Google 雲端硬碟下載 <a href='https://drive.google.com/drive/folders/1kLtgA67H7Hnzcb6cVsWGVN4OxnDCvj_5?usp=sharing'>https://drive.google.com/drive/folders/1kLtgA67H7Hnzcb6cVsWGVN4OxnDCvj_5?usp=sharing</a>",
        "en": "Grab drama clips <a href='https://drive.google.com/drive/folders/1kLtgA67H7Hnzcb6cVsWGVN4OxnDCvj_5?usp=sharing'>https://drive.google.com/drive/folders/1kLtgA67H7Hnzcb6cVsWGVN4OxnDCvj_5?usp=sharing</a>",
    },
    KocContentTip2: {
        "zh-TW": "Netshort 各平台官方帳號上可下載影片",
        "en": "Download from Netshort’s official accounts.",
    },
    KocContentBtn: {
        "zh-TW": "獲取資源",
        "en": "Download Resources",
    },
    KocCreateTitle: {
        "zh-TW": "✨ 創作示範",
        "en": "✨ Post Ideas (Easy & Fun!)"
    },
    KocCreateTip1: {
        "zh-TW": "範例1：短劇精彩片段剪輯 + 導流引導",
        "en": "Highlight scenes + your voiceover/reaction",
    },
    KocCreateTip2: {
        "zh-TW": "範例2：你本人 + 劇情反應/模仿 + App 下載引導",
        "en": " You + reaction + app promo<br/>" +
            " → “I was hooked after just one episode...” + your reaction or imitation + call to download",
    },
    KocCreateTip3: {
        "zh-TW": "範例3：自創有趣內容，只要跟 Netshort 有關都可以！",
        "en": "Skits, edits, cosplay — anything goes, as long as it’s Netshort-related!",
    },
    KocBonusAlertTitle: {
        "zh-TW": "🎁額外獎勵",
        "en": "🎁Bonus Alert"
    },
    KocBonusAlertTip1: {
        "zh-TW": "貼文按讚破 1,000 或瀏覽破 10,000 就有加碼獎！",
        "en": "Get 1,000+ likes or 10K+ views? We’ll throw in <span>extra rewards</span> 👀💥"
    },
    KocMoreRuleTitle: {
        "zh-TW": "規則補充",
        "en": "Rule Supplement",
    },
    KocMoreRuleTip1: {
        "zh-TW": "📅 活動時間：7/16 ～ 7/31（UTC+0）",
        "en": "📅 Event Time: July 16–31 (UTC+0)",
    },
    KocMoreRuleTip2: {
        "zh-TW": "🛑 每個帳號僅能參加一次",
        "en": "🛑 1 entry per account",
    },
    KocMoreRuleTip3: {
        "zh-TW": "🚫 禁止違規或虛假內容",
        "en": "🚫 No fake/misleading content",
    },
    KocMoreRuleTip4: {
        "zh-TW": "✔️ 最終解釋權歸 Netshort 所有",
        "en": "✅ Final interpretation rights belong to Netshort",
    },
    KocFinish: {
        "zh-TW": "📣 機會難得，發揮你的創意，來挑戰「發片賺金幣」吧！",
        "en": "Ready to show your creativity and get rewarded? Let’s go!",
    },
    KocDMUs: {
        "zh-TW": "有問題找 @Nina",
        "en": "DM us 👉 @NetshortHelpbot",
    },
    MessageNum: {
        "zh-TW": "訊息數量",
        "en": "Message Count",
        "ja": "メッセージ数",
        "ko": "메시지 수",
    },
    FissionNoGift: {
        "zh-TW": "參與活動領取獎勵喔～",
        "en": "Join the event to claim your reward~"
    },
    FissionTitle: {
        "zh-TW": "邀請好友，免費看劇",
        "en": "Invite Friends & Watch Drama for Free"
    },
    FissionTime: {
        "zh-TW": "僅限 Telegram",
        "en": "Only for Telegram",
    },
    FissionRedeem: {
        "zh-TW": "兌換",
        "en": "Redeem"
    },
    FissionBalance: {
        "zh-TW": "獎勵",
        "en": "Reward"
    },
    FissionLogin: {
        "zh-TW": "任務1 —— 50 積分",
        "en": "Task 1 -- 50points"
    },
    FissionClaimed: {
        "zh-TW": "已獲取",
        "en": "Claimed"
    },
    FissionClaim: {
        "zh-TW": "獲取",
        "en": "Claim"
    },
    FissionFollowChannel: {
        "zh-TW": "任務1 —— 100 積分",
        "en": "Task1 -- 100points",
    },
    FissionFollow:{
        "zh-TW": "關注",
        "en": "Follow",
    },
    FissionFollowed: {
        "zh-TW": "已關注",
        "en": "Followed",
    },
    FissionInviteFriend: {
        "zh-TW": "任務2 — 無上限",
        "en": "Task2 -- No limit",
    },
    FissionInvite: {
        "zh-TW": "邀請好友",
        "en": "Invite Friends",
    },
    FissionLoginTelegramDesc: {
        "zh-TW": "💬 登入 Telegram — Boom！100 積分就是你的！",
        "en": "💬 Log in to Telegram — Boom! 100 points are yours!",
    },
    FissionFollowChannelDesc: {
        "zh-TW": "📢 關注我們的官方頻道，再拿 100 積分！",
        "en": "📢 Follow our official channel and grab 100 points!"
    },
    FissionInviteDesc: {
        "zh-TW":"💡 每邀請一位好友參加活動，即可獲得 100 積分！邀越多，賺越多！",
        "en":"💡 Earn 100 points for every friend you bring to the event! The more, the better!"
    },
    FissionClaimSuccess: {
        "zh-TW": "獲取成功",
        "en": "Claim Success"
    },
    FissionRedeemSuccess: {
        "zh-TW": "兌換成功",
        "en": "Redeem Success"
    },
    FissionRedeemFailed: {
        "zh-TW": "需要 150 積分才可兌換",
        "en": "Requires 150 points to redeem"
    },
    FissionDesc: {
        "zh-TW": <>
<p>👉 完成任務，賺取積分，免費追劇！</p>
<p>🎯 150 積分 = 1 部劇集</p>
<p>✨ 積分越多，免費看的劇越多！</p>
<p>♾️ 無上限 — 持續賺積分，盡情追劇！</p>
        </>,
        "en": <>
            <p>👉 Do tasks, earn points, and watch dramas for free!</p>
            <p>🎯 150 points = 1 drama</p>
            <p>✨ The more points you earn, the more free dramas you get!</p>
            <p>♾️ No limit — keep earning, keep watching!</p>
        </>
    },
    FissionInviteTip: {
        "en": "Join the community, help friends, and watch the latest mini-dramas",
    },
    Activity: {
        "zh-TW": "近期活動",
        "en": "Recent Activities",
        "ja": "最近の活動",
    },
    DramaExpire: {
        "zh-TW": "抱歉，此短劇已下架",
        "en": "Sorry, this short drama is no longer available",
        "ja": "申し訳ありませんが、この短編映画は削除されました",
    },
    LineTitle1:{
        "zh-TW": <>LINE社群福利來了！</>,
        "en": <>LINE group rewards just dropped!</>,
        "ja": <>LINE特典が登場！</>
    },
    LineTitle2: {
        "zh-TW": <>關注官號&邀請好友<br/>免費看短劇！</>,
        "en": <>Watch dramas for free<br/>Follow us & Invite friends</>,
        "ja": <>公式フォロー＆友達招待<br/>ショドラ無料！</>,
    },
    LineGift: {
        "zh-TW": "🎁 禮物記錄",
        "en": "🎁 History",
        "ja": "🎁 ギフト履歴",
    },
    LineTip1: {
        "zh-TW": "火熱進行中",
        "en": "Hot & Live!",
        "ja": "“大好評開催中！",
    },
    LinePointBalance: {
        "zh-TW": "積分餘額",
        "en": "Balance",
        "ja": "保有ポイント",
    },
    LineTask: {
        "zh-TW": "🎯 獎勵任務",
        "en": "🎯 Challenge",
        "ja": "🎯 ご褒美タスク",
    },
    LineFollow: {
        "zh-TW": <>關注<a href='https://line.me/R/ti/p/@887dxxzh'>LINE 官號</a>領取獎勵</>,
        "en": <>🎁 Follow the <a href='https://line.me/R/ti/p/@887dxxzh'>LINE official account</a> to claim your reward</>,
        "ja": <><a href='https://lin.ee/p7xtiKE'>LINE公式アカウント</a>をフォローして報酬をゲット！</>,
    },
    LineClaim: {
        "zh-TW": "領取",
        "en": "Claim",
        "ja": "獲得"
    },
    LineClaimed:{
        "zh-TW": "🎉 已領取",
        "en": "🎉 Already Claimed",
        "ja": "🎉 受け取り済み"
    },
    LineInvite: {
        "zh-TW": "邀請好友",
        "en": "Invite Friends",
        "ja": "友達招待"
    },
    LineClaimTime: {
        "zh-TW": "領取時間",
        "en": "Claim Time",
        "ja": "受け取り時間"
    },
    LineGiftStatus: {
        "zh-TW": "狀態",
        "en": "Status",
        "ja": "ステータス",
    },
    LineGiftStatusPending:{
        "zh-TW": "待處理",
        "en": "Pending",
        "ja": "保留中",
    },
    LineGiftStatusCredited :{
        "zh-TW": "已到帳",
        "en": "Credited",
        "ja": "入金済み",
    },
    LineGiftStatusAvailable:{
        "zh-TW": "待使用",
        "en": "Available",
        "ja": "未使用",
    },
    LineGiftStatusUsed: {
        "zh-TW": "已使用",
        "en": "Used",
        "ja": "使用済み",
    },
    LineGiftClickToCopy: {
        "zh-TW": "點擊複製",
        "en": "Click to Copy",
        "ja": "クリックしてコピー",
    },
    LineGiftCode: {
        "zh-TW": "禮品碼",
        "en": "Gift Code",
        "ja": "ギフトコード"
    },
    LineClose: {
        "zh-TW": "關閉",
        "en": "Close",
        "ja": "閉じる",
    },
    LineGo: {
        "zh-TW": "前往",
        "en": "Go",
        "ja": "Go",
    },
    LineCouponDesc: {
        "zh-TW": "禮品碼可用於兌換短劇免費觀看。",
        "en": "Gift codes can be used to redeem free access to short dramas.",
        "ja": "ギフトコードは短編ドラマの無料視聴に使用できます。",
    },
    LineCoinDesc: {
        "zh-TW": "NetShort禮品金幣可用於購買NetShort APP中的短劇劇集。",
        "en": "NetShort gift coins can be used to purchase short drama episodes in the NetShort app.",
        "ja": "NetShortのギフトコインは、NetShortアプリ内の短編ドラマのエピソード購入に使用できます。",
    },
    LineShareDesc: {
        "zh-TW": "每邀請一位好友關注官號，都可以獲得一次獎勵。",
        "en": "Each time you invite a friend to follow the official account, you will receive a reward.",
        "ja": "友達を1人公式アカウントに招待してフォローさせるたびに、報酬がもらえます。",
    },
    LineFollowGroup: {
        "zh-TW": "🎉 福利加碼",
        "en": "🎉 More benefits",
        "ja": "🎉 もっと特典",
    },
    LineGroupDesc: {
        "zh-TW": "關注官方LINE社群，定期舉行福利活動，還有更多熱愛短劇的帥哥美女在群裡！",
        "en": "Follow the official LINE community! Regular reward events are held, and many short drama lovers — handsome guys and pretty girls — are waiting in the group!",
        "ja": "公式LINEコミュニティをフォローしよう！定期的に特典イベントを開催中。短編ドラマ好きのイケメンや美女もたくさん参加しています！",
    },
    LineRedeemSuccess: {
        "zh-TW": "兌換成功",
        "en": "Exchange Successful",
        "ja": "交換成功",
    },
    LineCodeInvalid: {
        "zh-TW": "驗證碼錯誤",
        "en": "Verification code error",
        "ja": "認証コードが間違っています",
    },
    LineAccountFollow: {
        "zh-TW": "你的Line已經綁定了其他的帳號。",
        "en": "Your Line is already linked to another account.",
        "ja": "あなたのLineはすでに他のアカウントに紐づけられています。",
    },
    LineBalanceInsufficient: {
        "zh-TW": "剩餘積分不足",
        "en": "Insufficient remaining points",
        "ja": "残りのポイントが不足しています",
    },
    LineWelcome: {
        "zh-TW": <>助力好友<br/>一起免費追新劇！</>,
        "en": <>Team up with friends<br/>watch new dramas free!</>,
        "ja": <>友達と協力<br/>最新ドラマを無料視聴！</>,
    },
    LineInviteFollowTip: {
        "zh-TW": <>   前往<a href='https://line.me/R/ti/p/@887dxxzh'>官方帳號</a>獲取驗證碼</>,
        "en": <>    Go to the <a href='https://line.me/R/ti/p/@887dxxzh'>official account</a> to get the verification code</>,
        "ja": <>   <a href='https://lin.ee/p7xtiKE'>公式アカウント</a>で認証コードを取得！</>
    },
    LineGiftEmpty: {
        "zh-TW": "暫時還沒有兌換到獎勵喔",
        "en": "Oops! No rewards redeemed yet",
        "ja": "まだ報酬をゲットしてないよ〜",
    },
    LineCodeAgain: {
        "zh-TW": "發送單詞 code 即可獲取新的驗證碼",
        "en": "Send the word \"code\" to receive a new verification code",
        "ja": "「code」と送信すると、新しい認証コードを受け取れます"
    },
    LinePlsLogin: {
        "zh-TW": "請先登入",
        "en": "Please log in first",
        "ja": "先にログインしてね",
    },
    LineAppIdInputTip: {
        "zh-TW": "複製你的 NetShort APP 使用者 ID",
        "en": "Copy your NetShort APP user ID",
        "ja": "NetShort アプリのユーザーIDをコピーしてください",
    },
    LineSave: {
        "zh-TW": "保存",
        "en": "Save",
        "ja": "保存する",
    },
    LineAppIdInputAsk: {
        "zh-TW": "填寫 NetShort App 使用者 ID，以便我們發放獎勵",
        "en": "Enter your NetShort App user ID so we can issue the reward",
        "ja": "NetShortアプリのユーザーIDを入力してください。報酬を配布するために必要です",
    },
    LineAppIdInvalid: {
        "zh-TW": "NetShortAPP 使用者 ID 為 19 位，請點擊複製按鈕獲取",
        "en": "The NetShort APP user ID is 19 digits long. Please click the copy button to get it",
        "ja": "NetShortアプリのユーザーIDは19桁です。コピーボタンをクリックして取得してください",
    }
}

export function getText(item){
    try {
        const userLang = navigator.language;
        const lang = userLang.split('-')[0];
        if(item[userLang]){
           return item[userLang]
        }else if (item[lang]){
            return item[lang]
        }else{
            return item["en"]
        }
    }catch (e){
        return "***"
    }
}